default: &default
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://127.0.0.1:6379') %>
  password: <%= ENV.fetch('REDIS_PASSWORD', nil).presence %>
  channel_prefix: <%= "chatwoot_#{Rails.env}_action_cable"  %>

development:
  <<: *default

test:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: <%= "chatwoot_#{Rails.env}_action_cable_test"  %>

staging:
  <<: *default

production:
  <<: *default
